[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"
autoexamples = false

[[example]]
name = "infrastructure_generate"
path = "examples/generate.rs"

[dependencies]
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
terrain-core = { path = "../terrain-core" }
thiserror = "2"
world-core = { path = "../world-core" }
urban = { path = "../urban" }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
